### ISSUE TITLE
Embeds for todos list

### ISSUE THREAD

**Issue by Prakhar896** [toasterclock/discordtimer#1]
# Proposal for an Embed for todo list
Make the todos message into an embed with each item entry to be its own field with the title as '{User's Tag}'s Todos'. Used in many other todos bots and might make this one more elegant.

Example:
![image](https://user-images.githubusercontent.com/53103894/123218880-d2e5f680-d4fe-11eb-9cfe-d581a58ce8cf.png)
Source: reminder-bot found on  http://top.gg

Possible methods using discord.py:
`e = discord.Embed(title="Hello there", description="This is an embed", color="#000000")`

More information could be found [here](https://python.plainenglish.io/send-an-embed-with-a-discord-bot-in-python-61d34c711046)

@toasterclock

**Comment by toasterclock** [comment]
Thank you for the feedback. Embeds for Todo Lists are now available!
![image](https://user-images.githubusercontent.com/64526036/123631269-20d56400-d849-11eb-9a07-80cf309c271d.png)
![image](https://user-images.githubusercontent.com/64526036/123631309-2e8ae980-d849-11eb-9601-1672a81a5101.png)

**Comment by Prakhar896** [comment]
great job! @toasterclock
